tinyMCE.addI18n('pt.table_dlg',{
general_tab:"Geral",
advanced_tab:"Avançado",
general_props:"Propriedades Gerais",
advanced_props:"Propriedades Avançadas",
rowtype:"Linha da Tabela",
title:"Inserir/Modificar Tabela",
width:"Tamanho",
height:"Altura",
cols:"Cols",
rows:"Rows",
cellspacing:"Cellspacing",
cellpadding:"Cellpadding",
border:"Borda",
align:"Alinhamento",
align_default:"Default",
align_left:"Esquerda",
align_right:"Direita",
align_middle:"Centro",
row_title:"Propriedades da Linha",
cell_title:"Propriedades da Célula",
cell_type:"Tipo de Célula",
valign:"Alinhamento Vertical",
align_top:"Acima",
align_bottom:"Abaixo",
bordercolor:"Cor da Borda",
bgcolor:"Cor de Fundo",
merge_cells_title:"Mesclar células",
id:"Id",
style:"Estilo",
langdir:"Language direction",
langcode:"Language code",
mime:"Target MIME type",
ltr:"Esquerda Para Direita",
rtl:"Direita Para Esquerda",
bgimage:"Imagens de Fundo",
summary:"Sumário",
td:"Dado",
th:"Cabeçalho",
cell_cell:"Atualizar célula atual",
cell_row:"Atualizar todas as células da linha",
cell_all:"Atualizar todas as células da tabela",
row_row:"Atualizar linha atual",
row_odd:"Atualizar linhas pares da tabela",
row_even:"Atualizar linhas ímpares da tabela",
row_all:"Atualizar todas as linhas da tabela",
thead:"Cabeçalho",
tbody:"Corpo",
tfoot:"Rodapé",
scope:"Escopo",
rowgroup:"Agrupar linha",
colgroup:"Agrupar coluna",
col_limit:"Você excedeu o número máximo de colunas {$cols}.",
row_limit:"Você excedeu o número máximo de linhas {$rows}.",
cell_limit:"Você excedeu o número máximo de células {$cells}.",
missing_scope:"Tem certeza que deseja continuar sem especificar o escopo do cabeçalho desta célula?. Sem isso, será difícil para alguns usuários desabilitar e entender o conteúdo exibido na tabela.",
caption:"Título da tabela",
frame:"Frame",
frame_none:"nome",
frame_groups:"agrupamentos",
frame_rows:"linhas",
frame_cols:"colunas",
frame_all:"tudo",
rules:"Regras",
rules_void:"Nenhum",
rules_above:"Acima",
rules_below:"Abaixo",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"caixa",
rules_border:"borda"
});