tinyMCE.addI18n(
'pt.advanced',{
	style_select:"Estilos",
	font_size:"Tamanho",
	snipdefault:"Conteúdo",
	fontdefault:"Fonte",
	block:"Formato",
	paragraph:"Paragrafo",
	div:"Div",
	address:"Endereço",
	pre:"Pré-formatado",
	h1:"Título 1",
	h2:"Título 2",
	h3:"Título 3",
	h4:"Título 4",
	h5:"Título 5",
	h6:"Título 6",
	blockquote:"Blockquote",
	code:"Code",
	samp:"Code sample",
	dt:"Definition term ",
	dd:"Definition description",
	bold_desc:"Negrito (Ctrl+B)",
	italic_desc:"Itálico (Ctrl+I)",
	underline_desc:"Sublinhado (Ctrl+U)",
	striketrough_desc:"Riscado",
	justifyleft_desc:"Alinhamento a Esquerda",
	justifycenter_desc:"Alinhamento Centralizado",
	justifyright_desc:"Alinhamento a Direita",
	justifyfull_desc:"Alinhamento Justificado",
	bullist_desc:"Marcadores",
	numlist_desc:"Numeração",
	outdent_desc:"Remover Identação",
	indent_desc:"Indentar",
	undo_desc:"Undo (Ctrl+Z)",
	redo_desc:"Redo (Ctrl+Y)",
	link_desc:"Editar Link",
	unlink_desc:"Remover Link",
	image_desc:"Editar Imagem",
	cleanup_desc:"Cleanup messy code",
	code_desc:"Edit HTML Source",
	sub_desc:"Subescrito",
	sup_desc:"Sobrescrito",
	hr_desc:"Inserir linha horizontal",
	removeformat_desc:"Remover formatação",
	custom1_desc:"Sua descrição vem aqui",
	forecolor_desc:"Selecionar cor da fonte",
	backcolor_desc:"Selecionar cor do realce",
	charmap_desc:"Inserir caracter especial",
	visualaid_desc:"Trocar linhas-guia/elementos invisíveis",
	anchor_desc:"Inserir/Editar ancora",
	cut_desc:"Cortar",
	copy_desc:"Copiar",
	paste_desc:"Colar",
	image_props_desc:"Propriedades da Imagem",
	newdocument_desc:"Novo documento",
	help_desc:"Ajuda",
	blockquote_desc:"Blockquote",
	clipboard_msg:"Copiar/Cortar/Colar não está disponível no Mozilla e Firefox.\r\nVocê quer saber mais informação sobre isso?",
	path:"Configuração do Texto",
	newdocument:"Tem certeza que deseja limpar todo o conteúdo?",
	toolbar_focus:"Ir para Botões da Barra de Ferramentas - Alt+Q, Ir para editor - Alt-Z, Ir para Caminho - Alt-X",
	more_colors:"Mais cores..."
	}
);